version: '3.8'

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: payment_db
    ports:
      - "6000:5000"
    depends_on:
      - payment-db       #error here
  payment-db:
    image: postgres:14.2-alpine #error here
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: payment_db
    ports:
      - "6000:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data #error here
