version: '3.8'

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: payment_db
    ports:
      - "6000:5000"
  payment-db:
    build: postgres:14.2-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: payment_db
    ports:
      - "6000:5432"
    volumes:
      - payment-db-vol:/var/lib/postgresql/data
