version: '3.8'
#Added volumes below
volumes:
  postgres-db:

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "5500:5000" # Not able to publish on same port so changed to 5500
    depends_on: # Added depends on
      - payment-db
  payment-db:
    #build: postgres:14.2-alpine
    image: postgres:14.2-alpine # it should be image not build
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "6000:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
