version: '3.8'

volumes:
  payment-db-vol:

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "6000:5000" #changed port other than 6000
    depends_on: # add dependencies to make sure payment-service depends on payment-db
          - payment-db
  payment-db:
    image: postgres:14.2-alpine #think it should be image,changed to image
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432" #remapped with its native port
    volumes:
      - payment-db-vol: /var/lib/postgresql/data
