version: '3.8'

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER: myUser #credentials
      POSTGRES_PASSWORD: myPassword #credentials
      POSTGRES_DB: payment_db
    ports:
      - "6000:5001" #change container port to 5001
  payment-db:
    build: postgres:14.2-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432" #change host port to 5432
    volumes:
      - payment-db-vol:/var/lib/postgresql/data
