version: '3.8'

volumes: # add volume to store data
  postgres-db:

services:
  payment-service:
    build: .
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "5000:5000"#  has conflit with port 6000.it should change to the other port than 6000
    depends_on: # add dependencies
      - payment-db
  payment-db:
    image: postgres:14.2-alpine #should be image not build
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: payment_db
    ports:
      - "6000:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
